In [35]:
import warnings 
warnings.filterwarnings('ignore')

In [36]:
import pandas as pd

In [37]:
data = pd.read_csv('car data.csv')

In [38]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    str
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    str
 6   Seller_Type    301 non-null    str
 7   Transmission   301 non-null    str
 8   Owner          301 non-null    int64
dtypes: float64(2), int64(3), str(4)
memory usage: 21.3 KB

In [39]:
data.describe()

              Year  Selling_Price  Present_Price     Kms_Driven       Owner
count   301.000000     301.000000     301.000000     301.000000  301.000000
mean   2013.627907       4.661296       7.628472   36947.205980    0.043189
std       2.891554       5.082812       8.644115   38886.883882    0.247915
min    2003.000000       0.100000       0.320000     500.000000    0.000000
25%    2012.000000       0.900000       1.200000   15000.000000    0.000000
50%    2014.000000       3.600000       6.400000   32000.000000    0.000000
75%    2016.000000       6.000000       9.900000   48767.000000    0.000000
max    2018.000000      35.000000      92.600000  500000.000000    3.000000

In [40]:
data.head()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,Ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0
1,Sx4,2013,4.75,9.54,43000,Diesel,Dealer,Manual,0
2,Ciaz,2017,7.25,9.85,6900,Petrol,Dealer,Manual,0
3,Wagon R,2011,2.85,4.15,5200,Petrol,Dealer,Manual,0
4,Swift,2014,4.60,6.87,42450,Diesel,Dealer,Manual,0

In [41]:
data.isnull()

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
296,False,False,False,False,False,False,False,False,False
297,False,False,False,False,False,False,False,False,False
298,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False

In [42]:
data.shape

(301, 9)

In [43]:
data.isnull().sum()

Car_Name         0
Year             0
Selling_Price    0
Present_Price    0
Kms_Driven       0
Fuel_Type        0
Seller_Type      0
Transmission     0
Owner            0
dtype: int64

In [44]:
data.head(1)

,Car_Name,Year,Selling_Price,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,Ritz,2014,3.35,5.59,27000,Petrol,Dealer,Manual,0

In [45]:
import datetime

In [46]:
date_time = datetime.datetime.now()
date_time.year

2026

In [47]:
import datetime

In [87]:
datadata = data.drop('Year',axis = 1)

In [ ]:
data.head(1)

In [ ]:
data['Age'] = date_time.Year - data['Year']

In [ ]:
import seaborn as sns

In [ ]:
sns.boxplot(data['Selling_Price'],orient="h")

In [ ]:
sorted(data['Selling_Price'],reverse=True)

In [49]:
data = data[~(data['Selling_Price']>=33.0)&(data['Selling_Price']<=35.0)]

In [50]:
sorted(data['Selling_Price'],reverse=True)

[23.5,
 23.0,
 23.0,
 23.0,
 20.75,
 19.99,
 19.75,
 18.75,
 18.0,
 17.0,
 16.0,
 14.9,
 14.73,
 14.5,
 14.25,
 12.9,
 12.5,
 11.75,
 11.5,
 11.45,
 11.25,
 11.25,
 11.25,
 10.9,
 10.25,
 10.11,
 9.7,
 9.65,
 9.5,
 9.25,
 9.25,
 9.25,
 9.15,
 9.1,
 8.99,
 8.75,
 8.65,
 8.55,
 8.5,
 8.4,
 8.4,
 8.35,
 8.25,
 8.25,
 7.9,
 7.75,
 7.75,
 7.75,
 7.5,
 7.5,
 7.5,
 7.45,
 7.45,
 7.45,
 7.4,
 7.25,
 7.25,
 7.2,
 7.05,
 6.95,
 6.85,
 6.75,
 6.7,
 6.6,
 6.5,
 6.5,
 6.45,
 6.4,
 6.25,
 6.25,
 6.15,
 6.1,
 6.0,
 6.0,
 6.0,
 6.0,
 5.95,
 5.95,
 5.9,
 5.85,
 5.85,
 5.8,
 5.75,
 5.75,
 5.65,
 5.5,
 5.5,
 5.5,
 5.5,
 5.5,
 5.4,
 5.4,
 5.35,
 5.3,
 5.3,
 5.25,
 5.25,
 5.25,
 5.25,
 5.25,
 5.25,
 5.25,
 5.2,
 5.15,
 5.11,
 5.0,
 4.95,
 4.95,
 4.9,
 4.9,
 4.85,
 4.8,
 4.8,
 4.75,
 4.75,
 4.75,
 4.75,
 4.75,
 4.75,
 4.65,
 4.6,
 4.5,
 4.5,
 4.5,
 4.5,
 4.5,
 4.5,
 4.5,
 4.4,
 4.4,
 4.4,
 4.35,
 4.15,
 4.1,
 4.1,
 4.0,
 4.0,
 4.0,
 4.0,
 4.0,
 3.95,
 3.95,
 3.9,
 3.9,
 3.8,
 3.75,
 3.75,
 3.65,
 3.6,
 3.51,
 3.5,
 3.5,
 3.49,
 3.45,
 3.35,
 3.35,
 3.25,
 3.25,
 3.25,
 3.15,
 3.1,
 3.1,
 3.1,
 3.1,
 3.0,
 3.0,
 3.0,
 3.0,
 2.95,
 2.95,
 2.9,
 2.9,
 2.9,
 2.85,
 2.85,
 2.85,
 2.75,
 2.75,
 2.7,
 2.65,
 2.65,
 2.65,
 2.55,
 2.55,
 2.5,
 2.5,
 2.35,
 2.25,
 2.25,
 2.25,
 2.1,
 2.0,
 1.95,
 1.95,
 1.75,
 1.7,
 1.65,
 1.5,
 1.45,
 1.35,
 1.35,
 1.35,
 1.25,
 1.25,
 1.2,
 1.2,
 1.2,
 1.15,
 1.15,
 1.15,
 1.15,
 1.11,
 1.1,
 1.1,
 1.1,
 1.05,
 1.05,
 1.05,
 1.05,
 1.05,
 1.0,
 0.95,
 0.9,
 0.9,
 0.8,
 0.78,
 0.75,
 0.75,
 0.75,
 0.75,
 0.72,
 0.65,
 0.65,
 0.65,
 0.65,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.6,
 0.55,
 0.55,
 0.52,
 0.51,
 0.5,
 0.5,
 0.5,
 0.5,
 0.5,
 0.48,
 0.48,
 0.48,
 0.48,
 0.45,
 0.45,
 0.45,
 0.45,
 0.45,
 0.45,
 0.45,
 0.45,
 0.42,
 0.42,
 0.4,
 0.4,
 0.4,
 0.4,
 0.4,
 0.38,
 0.38,
 0.35,
 0.35,
 0.35,
 0.35,
 0.31,
 0.3,
 0.3,
 0.3,
 0.27,
 0.25,
 0.25,
 0.25,
 0.25,
 0.25,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.2,
 0.18,
 0.17,
 0.16,
 0.15,
 0.12,
 0.1]

In [51]:
data.shape

(299, 9)

In [60]:
data['Fuel_Type'].unique()

array([nan])

In [61]:
data['Fuel_Type'] = data['Fuel_Type'].map({'petrol':0,'Diesel':1,'CNG':2})

In [62]:
data['Fuel_Type'].unique()

array([nan])

In [63]:
X = data.drop(['Car_Name','Selling_Price'],axis = 1)
y= data['Selling_Price']

In [64]:
y

0       3.35
1       4.75
2       7.25
3       2.85
4       4.60
       ...
296     9.50
297     4.00
298     3.35
299    11.50
300     5.30
Name: Selling_Price, Length: 299, dtype: float64

In [65]:
X

,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
0,2014,5.59,27000,NaN,Dealer,Manual,0
1,2013,9.54,43000,NaN,Dealer,Manual,0
2,2017,9.85,6900,NaN,Dealer,Manual,0
3,2011,4.15,5200,NaN,Dealer,Manual,0
4,2014,6.87,42450,NaN,Dealer,Manual,0
...,...,...,...,...,...,...,...
296,2016,11.60,33988,NaN,Dealer,Manual,0
297,2015,5.90,60000,NaN,Dealer,Manual,0
298,2009,11.00,87934,NaN,Dealer,Manual,0
299,2017,12.50,9000,NaN,Dealer,Manual,0
300,2016,5.90,5464,NaN,Dealer,Manual,0

###  splitting the data set into the trining set and teat set

In [ ]:
!pip install scikit-learn

In [ ]:
!pip install xgboost

In [ ]:
from  sklearn.model_selection import train_test_split

In [72]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.20,random_state=42)

In [73]:
X_train

,Year,Present_Price,Kms_Driven,Fuel_Type,Seller_Type,Transmission,Owner
6,2015,8.12,18796,NaN,Dealer,Manual,0
185,2008,0.58,1900,NaN,Individual,Automatic,0
187,2013,0.51,32000,NaN,Individual,Manual,0
148,2010,0.94,45000,NaN,Individual,Manual,0
30,2012,5.98,51439,NaN,Dealer,Manual,0
...,...,...,...,...,...,...,...
190,2008,0.75,60000,NaN,Individual,Manual,0
72,2013,18.61,56001,NaN,Dealer,Manual,0
108,2016,1.50,18000,NaN,Individual,Manual,0
272,2015,10.00,27600,NaN,Dealer,Manual,0
104,2017,1.47,4100,NaN,Individual,Manual,0

In [85]:
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.ensemble import GradientBoostingRegressor
from xgboost import XGBRegressor

In [86]:

# 1. Linear Regression
lr = LinearRegression()
lr.fit(X_train, y_train)

# 2. Random Forest Regressor
rf = RandomForestRegressor()
rf.fit(X_train, y_train)

# 3. Gradient Boosting Regressor
gb = GradientBoostingRegressor()
gb.fit(X_train, y_train)

# 4. XGBoost Regressor
xgb = XGBRegressor()
xgb.fit(X_train, y_train)

ValueError: could not convert string to float: 'Dealer'